### ISSUE TITLE
[Bug]: PHONE_REGISTRATION_ERROR

### ISSUE THREAD

**Issue by hauptanja** [bropat/eufy-security-client#140]
### Client version

1.6.6

### Node version

16.13.2

### Operating System type

Mac OS X

### Operating system version

macOS big sur 11.1

### Describe the bug

When i try to register a device in my electron - vue js app, i get the following error.

[2022-04-16 03:00:19.302] [error] registerGcm - Generic Error: Error: GCM-Register Error: PHONE_REGISTRATION_ERROR

I removed all of my registered devices from the official eufy electron app, but it did not help. 

### To reproduce

1. create new electron app with vue js and add eufy-security-client as dependency 
2. make production build 
3. log in with your credentials 
4. push notifications register fails 

`[2022-04-18 18:56:22.856] [error] registerGcm - Generic Error: Error: GCM-Register Error: PHONE_REGISTRATION_ERROR
    at h.registerGcm (/...*.app/Contents/Resources/app.asar/background.js:2:661059)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /...*.app/Contents/Resources/app.asar/background.js:2:658001
    at async h.createPushCredentials /...*.app/Contents/Resources/app.asar/background.js:2:657875)
    at async h._open (/...*.app/Contents/Resources/app.asar/background.js:2:668109)
........

[2022-04-18 18:56:22.856] [error] Create push credentials Error: Error: Google register to GCM failed with error: Error: GCM-Register Error: PHONE_REGISTRATION_ERROR
    at h.registerGcm /...*.app/Contents/Resources/app.asar/background.js:2:661236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async/...*.app/Contents/Resources/app.asar/background.js:2:658001
    at async h.createPushCredentials/...*.app/Contents/Resources/app.asar/background.js:2:657875)

......
[2022-04-18 18:56:22.860] [info]  Push notification connection closed
[2022-04-18 18:56:22.861] [error] Push notifications are disabled, because the registration failed!
[2022-04-18 18:56:22.861] [info]  Retry to register/login for push notification in 20 seconds...`

**Comment by hauptanja** [comment]
Development build works, production fails with the error described above 

Here are the logs for both: 
[prod-desktop.log](https://github.com/bropat/eufy-security-client/files/8609394/prod-desktop.log)
[dev-desktop.log](https://github.com/bropat/eufy-security-client/files/8609395/dev-desktop.log)

**Comment by bropat** [comment]
@hauptanja 

Try to delete the `persistent.json` file in the dev env and retry.

**Comment by hauptanja** [comment]
I have already tried that many times.
