### ISSUE TITLE
[Question]: T8520 Firmware 1.3.8 Support in the near future? 

### ISSUE THREAD

**Issue by mikekeil** [bropat/eufy-security-client#172]
### Ask your question

My eufy T8520 smart lock was recently upgraded to he 1.3.8.0 firmware (unwillingly).  I'm using the homeassistant integration, but noticed ever since the firmware upgrade the lock is unresponsive and continually logging an error: `Tried all hosts, no connection could be established`.

**Comment by zuohaot** [comment]
I also accidentally updated my T8520 to the latest firmware.. Surprisingly, I couldnt find a way to downgrade the firmware.
Hi @bropat , let me know if you need access to my door lock. I can try my best to help you get the access. Thanks.

**Comment by bropat** [comment]
To debug the cause i need access to the device. Could you please share your device with me (i need admin rights):

* [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com) (for EU)
* [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)

Thanks!

**Comment by zuohaot** [comment]
> To debug the cause i need access to the device. Could you please share your device with me (i need admin rights):
> 
> * [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com) (for EU)
> * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)
> 
> Thanks!

My account is in "Australia" region. Am I still be able to share it?

**Comment by roozbehv** [comment]
I also have this issue, below is my log with some text replaced with xxxxxx

2022-08-08 13:44:36.311  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-08-08 13:44:41.600  INFO  MQTT connection successfully established 
2022-08-08 13:44:41.836  INFO  Successfully registered to MQTT notifications for lock T8520xxxxxxx
2022-08-08 13:44:43.836  INFO  Connected to station T8520xxxxxxxx on host xxxxxxxx and port xxxx 
/usr/src/app/node_modules/eufy-security-client/build/http/station.js:315
            return ((_a = this.rawStation.devices[0]) === null || _a === void 0 ? void 0 : _a.device_sn) === this.rawStation.station_sn;
                                                 ^
TypeError: Cannot read properties of null (reading '0')
    at Station.isIntegratedDevice (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:315:50)
    at EufySecurity.onStationCommandResult (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:1351:25)
    at Station.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:351:72)
    at Station.emit (node:events:527:28)
    at Station.onCommandResponse (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:579:14)
    at P2PClientProtocol.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/http/station.js:32:56)
    at P2PClientProtocol.emit (node:events:527:28)
    at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:929:34)
    at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:891:26)
    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:718:26)

**Comment by bropat** [comment]
> > To debug the cause i need access to the device. Could you please share your device with me (i need admin rights):
> > 
> > * [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com) (for EU)
> > * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)
> > 
> > Thanks!
> 
> My account is in "Australia" region. Am I still be able to share it?

Yeah.

**Comment by zuohaot** [comment]
@bropat I've sent the share request. Thanks!

**Comment by bropat** [comment]
@zuohaot 

What is not working for you or what error are you getting?

**Comment by zuohaot** [comment]
> @zuohaot
> 
> What is not working for you or what error are you getting?

I'm sorry Bropat. I think I was just dumb.. I thought 1.3.8.0 was not supported according the wiki page of known-working-device list. Now, I realised that my error was simply caused by low acoount permission rights..

Maybe we can update the list as 1.3.8.0 is supported now?

Anyhow, it is working now. Thanks for your excellent project!!

**Comment by roozbehv** [comment]
I can only get the baterry level... I'm not seeing the lock status. Are you seeing your lock status @zuohaot

**Comment by zuohaot** [comment]
> I can only get the baterry level... I'm not seeing the lock status. Are you seeing your lock status @zuohaot

Yes, I can see the lock status, battery level as well as control the lock. I use Home Assistant with it btw. I also tried on Homebridge. It also worked.

**Comment by roozbehv** [comment]
Ahhh mine is working too now... Had to update to the latest version of the integration 🙂

**Comment by bropat** [comment]
@zuohaot 

I have found an error in the emitting of the locked event. I will try to fix it tonight.
Can you keep the sharing going until tonight so I can test it?

**Comment by bropat** [comment]
@zuohaot 

I fixed the locked event in the `develop` branch (will be released in the next version). You can remove the device sharing.

Thanks!

**Comment by bropat** [comment]
@zuohaot 

> Maybe we can update the list as 1.3.8.0 is supported now?

I have also added the firmware version `1.3.8.0` as tested in the documentation.

Note: The column `Tested version` means what firmware version was tested by me and certified as working. It does not necessarily mean not supported. ;) Not supported is when you find a red cross under the column `Support status`.
