### ISSUE TITLE
[Bug]: guard mode changes crash the client

### ISSUE THREAD

**Issue by thieren** [bropat/eufy-security-client#187]
### Client version

2.1.1

### Node version

16.16.0

### Operating System type

Windows

### Operating system version

Windows 10

### Describe the bug

With the new alarm delay event the library crashes on Homebase 2. See [this issue]() for more information.
I'll provide a log of the eufy-security-client later. For now I only have the error message.

### To reproduce

Calling this.eufyStation.setGuardMode(mode) with any approbiate mode.

### Screenshots & Logfiles

```
[7/21/2022, 8:51:34 AM] [EufySecurity-2.1.0-beta.11] DEBUG: Homebase SET StationGuardMode (raw value homekit):0
[7/21/2022, 8:51:34 AM] [EufySecurity-2.1.0-beta.11] DEBUG: Homebase SET StationGuardMode:1
[7/21/2022, 8:51:34 AM] [EufySecurity-2.1.0-beta.11] INFO:  Homebase Request to change station guard mode to: Home.
[7/21/2022, 8:51:34 AM] [EufySecurity-2.1.0-beta.11] DEBUG: Homebase ON handlePropertyChange: { name: 'guardMode', value: 1 }
[7/21/2022, 8:51:34 AM] [EufySecurity-2.1.0-beta.11] DEBUG: Homebase ON handleRawPropertyChange: { type: 1151, value: '1' }
[7/21/2022, 8:51:34 AM] [EufySecurity-2.1.0-beta.11] DEBUG: Homebase ON SecuritySystemCurrentState: 1
[7/21/2022, 8:51:34 AM] [EufySecurity-2.1.0-beta.11] DEBUG: Homebase ON handlePropertyChange: { name: 'currentMode', value: 1 }
TypeError: Cannot read properties of undefined (reading 'toString')
    at Station.getArmDelay (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\http\station.ts:596:85)
    at Station.onAlarmMode (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\http\station.ts:566:31)
    at P2PClientProtocol.<anonymous> (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\http\station.ts:54:68)
    at P2PClientProtocol.emit (node:events:527:28)
    at P2PClientProtocol.handleDataControl (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\p2p\session.ts:1274:22)
    at P2PClientProtocol.handleData (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\p2p\session.ts:988:18)
    at P2PClientProtocol.parseDataMessage (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\p2p\session.ts:979:26)
    at P2PClientProtocol.handleMsg (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\p2p\session.ts:801:26)
    at Socket.<anonymous> (C:\Users\Rene\AppData\Roaming\npm\node_modules\homebridge-eufy-security\node_modules\eufy-security-client\src\p2p\session.ts:113:56)
    at Socket.emit (node:events:527:28)
[21.7.2022, 08:51:34] [homebridge-eufy-security] Child bridge process ended
```

**Comment by bropat** [comment]
@Palmke Could you have a look at this?

**Comment by Palmke** [comment]
Sure.
@thieren can you paste the security settings?
And also, am I correct to assume you are using HomeKit?

**Comment by thieren** [comment]
Hey @Palmke yep using eufy through homebridge-eufy-security. The error happens when changing to any mode (1, 0, 3, 63) did not try any other but am pretty sure this would also happen with other custom modes.

Let me know if you need other infos.

**Comment by Palmke** [comment]
I assumed that if you have a Homebase 2, you _must_ have the security mode data.
So I guess HomeKit enabled messes with that... I have commited a fix, but I kinda wanna know why the property isn't read for a Homebase (which has the alarm system built in) :-).

**Comment by thieren** [comment]
> I assumed that if you have a Homebase 2, you _must_ have the security mode data.
> 
> So I guess HomeKit enabled messes with that... I have commited a fix, but I kinda wanna know why the property isn't read for a Homebase (which has the alarm system built in) :-).
> 
> 

I don't quite follow you. Language barrier I think. ;-)

I don't think that HomeKit messes with anything since the plugin just acts as a proxy between the home app and the eufy client. There is no direct interaction.

I also don't really understand what you mean with _security mode data_. Sorry.

As said: will supply a log output from eufy-security-client as soon as I can. But could take a day or two.

**Comment by Palmke** [comment]
I mean Apple HomeKit, not the homebridge plugin you mentioned.
If the log output contains all the parameters from the homebase then that's fine.
The error where this client cannot find the property containing the security modes should be impossible.
This is what I mean with security mode data as you see it on your phone:

https://forumus-uploads-production.s3.dualstack.us-west-2.amazonaws.com/security/optimized/3X/5/4/5489741ad1bc29df6a12b7c384e54839160b397a_2_225x500.jpeg

**Comment by thieren** [comment]
Ok, my alarm delay is set to 0 seconds. Leaving delay is also 0 seconds.

The HomeKit thing I still don't understand. The Homebase is not connected in any other way, other then the plugin. (Yeah there's a HomeKit option in the eufy app, but as far as I could make out, this doesn't do anything).

**Comment by thieren** [comment]
I have tested setting something other than 0 seconds to the security settings, since I guessed that eufy might ignore these settings altogether if 0 seconds is chosen, but no. Even if I set 15 seconds for both settings it still crashes.

**Comment by Palmke** [comment]
When possible show me the parameters of the homebase.

**Comment by thieren** [comment]
Sry. Where do I find these?

**Comment by Palmke** [comment]
It's just the logging from the client. If you set it to `debug` that should be sufficient.
The client will spit out all its known parameters for all devices. If you paste the data from your Homebase 2 I can get a better understanding of what's going on.

**Comment by thieren** [comment]
Seems to me that the needed parameters (1157 = CMD_ALARM_DELAY_HOME, 1158...) are there, aren't they?

```
"T8010P*": {
        "station_id": 1295237,
        "station_sn": "T8010P****",
        "station_name": "Homebase",
        "station_model": "T8010",
        "time_zone": "CET-1CEST,M3.5.0,M10.5.0/3|1.1375",
        "wifi_ssid": "P0",
        "ip_addr": "**",
        "wifi_mac": "**",
        "sub1g_mac": "**",
        "main_sw_version": "3.1.9.0h",
        "main_hw_version": "P0",
        "sec_sw_version": "1.3.0.9",
        "sec_hw_version": "P0",
        "volume": "Anker_VBJk5nfCS",
        "main_sw_time": 1653397987,
        "setup_code": "*",
        "setup_id": "*",
        "device_type": 0,
        "event_num": 7597,
        "sku_number": "",
        "lot_number": "",
        "cpuid": "",
        "create_time": 1604969982,
        "update_time": 1658422778,
        "status": 1,
        "station_status": 0,
        "status_change_time": 0,
        "p2p_did": "*",
        "push_did": "*",
        "p2p_license": "MKHIZG",
        "push_license": "",
        "ndt_did": "*",
        "ndt_license": "",
        "wakeup_flag": 1,
        "p2p_conn": "*",
        "app_conn": "*",
        "wipn_enc_dec_key": "ZXSecurity17Cam@",
        "wipn_ndt_aes128key": "ZXSecurity17Cam@",
        "query_server_did": "*",
        "prefix": "*",
        "wakeup_key": "*",
        "member": {
          "family_id": 0,
          "station_sn": "T8010P*",
          "admin_user_id": "*",
          "member_user_id": "*",
          "short_user_id": "",
          "member_type": 1,
          "permissions": 0,
          "member_nick": "",
          "action_user_id": "",
          "fence_state": 0,
          "extra": "",
          "member_avatar": "",
          "house_id": "",
          "create_time": 1648234650,
          "update_time": 0,
          "status": 0,
          "email": "",
          "nick_name": "",
          "avatar": "",
          "action_user_email": "*",
          "action_user_name": "*"
        },
        "params": [
          {
            "param_id": 0,
            "station_sn": "T8010P*",
            "param_type": 1157,
            "param_value": "eyJkZXZpY2VzIjpbeyJkZXZpY2VfY2hhbm5lbCI6MCwiYWN0aW9uIjoxNjc3NzIyNX1dLCJjb3VudF9kb3duX2FsYXJtIjp7ImNoYW5uZWxfbGlzdCI6WzBdLCJkZWxheV90aW1lIjowfSwibW9kZV9pZCI6MSwiY291bnRfZG93bl9hcm0iOnsiY2hhbm5lbF9saXN0IjpbMF0sImRlbGF5X3RpbWUiOjB9LCJhY2NvdW50X2lkIjoiNGZmMjM4MWZiMjhhZWE2ODVjNGZlZTJiNTZkMjIwOGJhZmY2YmRmYSJ9",
            "create_time": 1658404643,
            "update_time": 1658404737,
            "status": 1
          },
          {
            "param_id": 5913553,
            "station_sn": "T8010P*",
            "param_type": 1292,
            "param_value": "",
            "create_time": 1610810658,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913364,
            "station_sn": "T8010P*",
            "param_type": 1236,
            "param_value": "1",
            "create_time": 1610810438,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913381,
            "station_sn": "T8010P*",
            "param_type": 1670,
            "param_value": "0",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913368,
            "station_sn": "T8010P*",
            "param_type": 1283,
            "param_value": "1",
            "create_time": 1610810438,
            "update_time": 1610810438,
            "status": 1
          },
          {
            "param_id": 25184502,
            "station_sn": "T8010P*",
            "param_type": 1264,
            "param_value": "eyJlbmFibGUiOjEsInNzaWQiOiJTdHJlaWNoZWx6b28iLCJic3NpZCI6ImRjOjE1OmM4OjU3OmRhOmQyIiwic2VjdXJpdHkiOiJXUEEyUFNLL0FFUyIsInBhc3N3b3JkIjoidGVycmFzc2VubmFja3RncmlsbGVuIiwiYWNjb3VudF9pZCI6IjRmZjIzODFmYjI4YWVhNjg1YzRmZWUyYjU2ZDIyMDhiYWZmNmJkZmEifQ==",
            "create_time": 1649067787,
            "update_time": 1649067787,
            "status": 1
          },
          {
            "param_id": 0,
            "station_sn": "T8010P*",
            "param_type": 1158,
            "param_value": "eyJkZXZpY2VzIjpbeyJkZXZpY2VfY2hhbm5lbCI6MCwiYWN0aW9uIjo5fV0sImNvdW50X2Rvd25fYWxhcm0iOnsiY2hhbm5lbF9saXN0IjpbMF0sImRlbGF5X3RpbWUiOjB9LCJtb2RlX2lkIjowLCJjb3VudF9kb3duX2FybSI6eyJjaGFubmVsX2xpc3QiOlswXSwiZGVsYXlfdGltZSI6MH0sImFjY291bnRfaWQiOiI0ZmYyMzgxZmIyOGFlYTY4NWM0ZmVlMmI1NmQyMjA4YmFmZjZiZGZhIn0=",
            "create_time": 1658404655,
            "update_time": 1658404755,
            "status": 1
          },
          {
            "param_id": 5913379,
            "station_sn": "T8010P*",
            "param_type": 1155,
            "param_value": "2",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913378,
            "station_sn": "T8010P*",
            "param_type": 1257,
            "param_value": "63",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913383,
            "station_sn": "T8010P*",
            "param_type": 1200,
            "param_value": "4",
            "create_time": 1610810441,
            "update_time": 1610810441,
            "status": 1
          },
          {
            "param_id": 5913363,
            "station_sn": "T8010P*",
            "param_type": 1224,
            "param_value": "1",
            "create_time": 1610810438,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913372,
            "station_sn": "T8010P*",
            "param_type": 1253,
            "param_value": "1",
            "create_time": 1610810438,
            "update_time": 1645110166,
            "status": 1
          },
          {
            "param_id": 5913377,
            "station_sn": "T8010P*",
            "param_type": 1266,
            "param_value": "-4",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 14121441,
            "station_sn": "T8010P*",
            "param_type": 1296,
            "param_value": "EU",
            "create_time": 1631022911,
            "update_time": 1631022911,
            "status": 1
          },
          {
            "param_id": 5913370,
            "station_sn": "T8010P*",
            "param_type": 1285,
            "param_value": "0",
            "create_time": 1610810438,
            "update_time": 1610810438,
            "status": 1
          },
          {
            "param_id": 5913380,
            "station_sn": "T8010P*",
            "param_type": 1176,
            "param_value": "10.6.6.53",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913376,
            "station_sn": "T8010P*",
            "param_type": 1265,
            "param_value": "2",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913366,
            "station_sn": "T8010P*",
            "param_type": 1281,
            "param_value": "1",
            "create_time": 1610810438,
            "update_time": 1610810438,
            "status": 1
          },
          {
            "param_id": 5913367,
            "station_sn": "T8010P*",
            "param_type": 1282,
            "param_value": "1",
            "create_time": 1610810438,
            "update_time": 1610810438,
            "status": 1
          },
          {
            "param_id": 5913369,
            "station_sn": "T8010P*",
            "param_type": 1284,
            "param_value": "0",
            "create_time": 1610810438,
            "update_time": 1610810438,
            "status": 1
          },
          {
            "param_id": 5913375,
            "station_sn": "T8010P*",
            "param_type": 1043,
            "param_value": "0",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 23826157,
            "station_sn": "T8010P*",
            "param_type": 1102,
            "param_value": "899",
            "create_time": 1646722240,
            "update_time": 1646722240,
            "status": 1
          },
          {
            "param_id": 5913365,
            "station_sn": "T8010P*",
            "param_type": 1230,
            "param_value": "26",
            "create_time": 1610810438,
            "update_time": 1610810438,
            "status": 1
          },
          {
            "param_id": 25184972,
            "station_sn": "T8010P*",
            "param_type": 1235,
            "param_value": "4",
            "create_time": 1649068423,
            "update_time": 1654005652,
            "status": 1
          },
          {
            "param_id": 5913382,
            "station_sn": "T8010P*",
            "param_type": 1280,
            "param_value": "0",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 6006918,
            "station_sn": "T8010P*",
            "param_type": 1256,
            "param_value": "eyJtb2RlcyI6W3siZG9vcnNlbnNvcl9hY3Rpb24iOjgsInRpdGxlIjoiIiwiZGV0YWlsIjoiIiwiaWNvblR5cGUiOjk5NiwibW9kZSI6MSwibW9kZV9hY3Rpb24iOjl9LHsiZG9vcnNlbnNvcl9hY3Rpb24iOjgsInRpdGxlIjoiIiwiZGV0YWlsIjoiIiwiaWNvblR5cGUiOjk5NSwibW9kZSI6MCwibW9kZV9hY3Rpb24iOjl9LHsiZG9vcnNlbnNvcl9hY3Rpb24iOjgsInRpdGxlIjoiTGVpc2UiLCJkZXRhaWwiOiIiLCJpY29uVHlwZSI6NiwibW9kZSI6MywibW9kZV9hY3Rpb24iOjl9XSwibW9kZV9pZCI6Mywib3BlcmF0ZV90eXBlIjoxMDAsImFjY291bnRfaWQiOiI0ZmYyMzgxZmIyOGFlYTY4NWM0ZmVlMmI1NmQyMjA4YmFmZjZiZGZhIn0=",
            "create_time": 1611144711,
            "update_time": 1611144711,
            "status": 1
          },
          {
            "param_id": 5913371,
            "station_sn": "T8010P*",
            "param_type": 1135,
            "param_value": "0",
            "create_time": 1610810438,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 5913373,
            "station_sn": "T8010P*",
            "param_type": 1362,
            "param_value": "1",
            "create_time": 1610810438,
            "update_time": 1610810438,
            "status": 1
          },
          {
            "param_id": 5913374,
            "station_sn": "T8010P*",
            "param_type": 1133,
            "param_value": "0",
            "create_time": 1610810441,
            "update_time": 1658422777,
            "status": 1
          },
          {
            "param_id": 0,
            "station_sn": "T8010P*",
            "param_type": 1140,
            "param_value": "1",
            "create_time": 1658279344,
            "update_time": 0,
            "status": 1
          }
        ],
        "devices": [
          {
            "device_id": 2153808,
            "is_init_complete": false,
            "device_sn": "T8210P*",
            "device_name": "Doorbell",
            "device_model": "T8210",
            "time_zone": "",
            "device_type": 7,
            "device_channel": 0,
            "station_sn": "T8010P*",
            "schedule": "",
            "schedulex": "",
            "wifi_mac": "*",
            "sub1g_mac": "*",
            "main_sw_version": "2.2.3.3",
            "main_hw_version": "T8210",
            "sec_sw_version": "1.1.52",
            "sec_hw_version": "T8210",
            "sector_id": 0,
            "event_num": 2,
            "wifi_ssid": "",
            "ip_addr": "",
            "main_sw_time": 1620740762,
            "sec_sw_time": 1650980990,
            "bind_time": 1610811170,
            "cover_path": "/thumb/2022/07/21/station/T8010P*/qdEnZVjuhLtaowtY.jpg",
            "cover_time": 1658416362,
            "local_ip": "",
            "language": "",
            "sku_number": "",
            "lot_number": "",
            "cpuid": "",
            "create_time": 1604279893,
            "update_time": 1658416393,
            "status": 1
          }
        ],
        "sensor_info": null,
        "is_init_complete": false,
        "virtual_version": "",
        "house_id": "*"
      }
```

**Comment by Palmke** [comment]
Not all the parameters are present from what I can tell by looking at the data:
```
    ARM_DELAY_AWAY = 1158,
    ARM_DELAY_CUS1 = 1159,
    ARM_DELAY_CUS2 = 1160,
    ARM_DELAY_CUS3 = 1161,
    ARM_DELAY_HOME = 1157,
    ARM_DELAY_OFF = 1180,
```
Your snippet seems to be missing `ARM_DELAY_CUS1`, `ARM_DELAY_CUS2`, `ARM_DELAY_CUS3` and `ARM_DELAY_OFF`. However, `HOME` and `AWAY` _are_ present and based on the data, the logic should work for switching _to_ `HOME` _and_ `AWAY`.

Assuming the property got parsed correctly by the client, `PropertyName.StationHomeSecuritySettings` and `PropertyName.StationAwaySecuritySettings` should have a value. 

This means the error you posted could not have happened because on this [line](https://github.com/bropat/eufy-security-client/blob/master/src/http/station.ts#L596), the error happens. The client tries to make a string out of the property's value.
I can see why this happens for your missing parameters, not for the mode you switched to: `HOME` (`1`).

Regardless of this weird behaviour, a fix has been merged this morning to the `develop` branch.
Have you tested again with that latest commit?

**Comment by thieren** [comment]
Yep. Have tested and is not crashing anymore.

But have not tested for delayed alarms, so if it works correctly if I set a delay whether it works as intended I can not say yet. But will do that later.

**Comment by Palmke** [comment]
@thieren I have pushed a commit which fixes an issue.
The away mode data incorrectly read from the custom1 mode parameter which would explain why you had a crash when switching to away.

**Comment by thieren** [comment]
@Palmke Ok, will try again and report back.

I think this will also revive my earlier assumption that the station only has this parameter if the delay values were set once. I only tested setting these for home and away and these two are the only ones found in the station params.
Will see if it fills the other ones if I set values there.

**Comment by thieren** [comment]
Seems to work just fine now. Thx for the fix!

**Comment by Palmke** [comment]
Cool. Apologies for messing it up in the first place 😅

**Comment by bropat** [comment]
> @Palmke Ok, will try again and report back.
> 
> I think this will also revive my earlier assumption that the station only has this parameter if the delay values were set once.

I can confirm that. I have already seen it for other parameters, which is why `eufy-security-client` also sets some parameters to default values if they are not available.

**Comment by Palmke** [comment]
I assume wrong probably because the `OFF` mode returned empty JSON array. 
I assumed this would be the case for all modes as I didn't change any settings for that mode ever.
