### ISSUE TITLE
[Bug]:  LivestreamNotRunningError

### ISSUE THREAD

**Issue by alinhayati** [bropat/eufy-security-client#212]
### Client version

2.2.0-rc.2

### Node version

16.14

### Operating System type

Linux

### Operating system version

Raspbian GNU/Linux 10 (buster)

### Describe the bug

It happens when downloading multiple files from the station. 

### To reproduce

Download a large number of videos (say 20) from the station, one after another, and you will this error coming up.

### Screenshots & Logfiles

Sep 15 04:23:06: ../node_modules/eufy-security-client/build/http/station.js:3204
Sep 15 04:23:06:             throw new error_2.LivestreamNotRunningError(`Livestream for device ${device.getSerial()} is not running`);
Sep 15 04:23:06:                   ^
Sep 15 04:23:06: LivestreamNotRunningError: Livestream for device xxxxx is not running
Sep 15 04:23:06:     at Station.stopLivestream (../node_modules/eufy-security-client/build/http/station.js:3204:19)
Sep 15 04:23:06:     at ../node_modules/eufy-security-client/build/eufysecurity.js:1343:21
Sep 15 04:23:06:     at runMicrotasks (<anonymous>)
Sep 15 04:23:06:     at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Additional context

I have rooted the issue down to this:
In `eufysecurity.js` when

**Comment by alinhayati** [comment]
I have rooted the issue down to this:
In `eufysecurity.js` in the listener  
`onErrorStationLivestream(station, channel, _error) {
        this.getStationDevice(station.getSerial(), channel).then((device) => {
            **station.stopLivestream(device);**
        }).catch((error) => {
            this.log.error(`Station livestream error (station: ${station.getSerial()} channel: ${channel} error: ${_error}})`, error);
        });
    }`
The highlighted line throws an error, which is not caught, due to the station not livestreaming at the time the listener is called, as in here:
`    async stopLivestream(device) {
        const commandData = {
            name: types_1.CommandName.DeviceStopLivestream
        };
        if (device.getStationSerial() !== this.getSerial()) {
            throw new error_1.WrongStationError(`Device ${device.getSerial()} is not managed by this station ${this.getSerial()}`);
        }
        if (!device.hasCommand(types_1.CommandName.DeviceStopLivestream)) {
            throw new error_1.NotSupportedError(`This functionality is not implemented or supported by ${device.getSerial()}`);
        }
        if (!this.isLiveStreaming(device)) {
            **throw new error_2.LivestreamNotRunningError(`Livestream for device ${device.getSerial()} is not running`);**
        }
        this.log.debug(`Sending stop livestream command to station ${this.getSerial()} for device ${device.getSerial()}`);
        await this.p2pSession.sendCommandWithInt({
            commandType: types_2.CommandType.CMD_STOP_REALTIME_MEDIA,
            value: device.getChannel(),
            channel: device.getChannel()
        }, {
            command: commandData
        });
    }`
