### ISSUE TITLE
[Bug]: Memory leak due to new dependency mediainfo.js in latest update

### ISSUE THREAD

**Issue by thieren** [bropat/eufy-security-client#271]
### Client version

latest

### Node version

16

### Operating System type

Linux

### Operating system version

-

### Describe the bug

There seems to be a memory leak in the latest update due to mediainfo.js

If a stream is frequently opened and closed it will result in the following warning from node (I enabled the full stack trace with --trace-warnings)

```
(node:2382) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at process.addListener (node:events:619:10)
    at MediaInfoModuleFactory (/Users/rene/dev/homebridge-plugins/homebridge-eufy-security/node_modules/mediainfo.js/build/MediaInfoModule.js:9:1855)
    at MediaInfoFactory (/Users/rene/dev/homebridge-plugins/homebridge-eufy-security/node_modules/mediainfo.js/src/mediainfo.ts:198:3)
    at /Users/rene/dev/homebridge-plugins/homebridge-eufy-security/node_modules/mediainfo.js/src/mediainfo.ts:177:45
    at new Promise (<anonymous>)
    at MediaInfoFactory (/Users/rene/dev/homebridge-plugins/homebridge-eufy-security/node_modules/mediainfo.js/src/mediainfo.ts:177:12)
    at analyzeCodec (/Users/rene/dev/homebridge-plugins/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/utils.ts:440:49)
    at P2PClientProtocol.handleDataBinaryAndVideo (/Users/rene/dev/homebridge-plugins/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:1428:37)
```

It seems as if the repo `mediainfo.js` has already an issue open for this: https://github.com/buzz/mediainfo.js/issues/89 but to me it is not obvious if this will be resolved in the near future.

A user that heavily uses the homebridge plugin has also reported that this leads to using up all of his memory after approximately 24h (https://github.com/homebridge-eufy-security/plugin/issues/243).

So my question would be: is it necessary to utilise the new dependency here?

### To reproduce

start and stop a stream frequently. Should happen after 10-20 times I think. Could reproduce quite regularly with the homebridge plugin.

**Comment by azavisha** [comment]
Since this update, I'm also consistently getting warnings about a potential memory leak and then a crash when it runs out of heap memory after downloading about a couple dozen videos. Trace points to mediainfo.

`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

`JavaScript heap out of memory`
