### ISSUE TITLE
[Bug]: Adapter is terminating

### ISSUE THREAD

**Issue by GreatEMU** [bropat/eufy-security-client#279]
### Client version

0.9.8

### Node version

16.16.0

### Operating System type

Docker

### Operating system version

20.10.03

### Describe the bug

When starting ioBroker or restart this adapter it is terminated by iobroker.
I am using the Homebase 2 with 2 eufyCams.

Here are the log enries:
2022-12-18 12:12:09.332	info	starting. Version 0.9.8 in /opt/iobroker/node_modules/iobroker.eusec, node: v16.16.0, js-controller: 4.0.23
2022-12-18 12:12:51.391	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-12-18 12:12:51.392	error	unhandled promise rejection: getaddrinfo EAI_AGAIN extend.eufylife.com
2022-12-18 12:12:51.393	error	RequestError: getaddrinfo EAI_AGAIN extend.eufylife.com at ClientRequest.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/node_modules/got/dist/source/core/index.js:970:111) at Object.onceWrapper (node:events:642:26) at ClientRequest.emit (node:events:539:35) at ClientRequest.origin.emit (/opt/iobroker/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20) at TLSSocket.socketErrorListener (node:_http_client:454:9) at TLSSocket.emit (node:events:527:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21) at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
2022-12-18 12:12:51.394	error	Exception-Code: EAI_AGAIN: getaddrinfo EAI_AGAIN extend.eufylife.com
2022-12-18 12:12:51.403	info	terminating

### To reproduce

Just start the adapter

**Comment by GreatEMU** [comment]
Falschen Adapter ausgewählt!
