### ISSUE TITLE
[Bug]: Lock.getPropertiesMetadata tried to read properties of undefined

### ISSUE THREAD

**Issue by MatthewHou** [bropat/eufy-security-client#352]
### Client version

2.4.2

### Node version

v18.16.0

### Operating System type

Linux

### Operating system version

Raspbian GNU/Linux Bullseye

### Describe the bug

My Homebridge Eufy Security plugin is crush looping because the security-client keep throwing this exception 

`TypeError: Cannot read properties of undefined (reading 'motionDetectionType')
    at Lock.getPropertiesMetadata (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:607:68)
    at Lock.update (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:50:31)
    at Lock.initializeState (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:37:14)
    at Function.initialize (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/device.ts:2284:14)
    at EufySecurity.handleDevices (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:549:39)
    at HTTPApi.<anonymous> (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/eufysecurity.ts:160:63)
    at HTTPApi.emit (node:events:513:28)
    at HTTPApi.refreshDeviceData (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/api.ts:584:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HTTPApi.refreshAllData (/var/lib/homebridge/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/api.ts:600:9)` 

I have a HB3, 4 S330 cameras (T8160) and 1 S330 lock (T8530). 

### To reproduce

1. Set up a HB3 and connect the S330 video lock to HB3
2. Install Eufy Security Plugin 2.2.0-beta.19 in Homebridge 1.6.1

**Comment by bropat** [comment]
Before opening a bug, use the latest version of the library and check whether the bug is still present there.
The T8530 lock is not yet supported.

Possible workaround:
Create a separate Eufy account and share all devices with admin rights except the lock. Then use this account with the plug-in.

**Comment by MatthewHou** [comment]
Unfortunately the proposed workaround doesn't work. Device sharing with admin right is limited to share all devices linked to the home base ![image](https://github.com/bropat/eufy-security-client/assets/24237992/a79da560-f473-4a07-8d04-e7c79d2cb863)
