### ISSUE TITLE
[Bug]: Non Parsable parameter

### ISSUE THREAD

**Issue by martijnpoppen** [bropat/eufy-security-client#357]
### Client version

2.7.1

### Node version

16

### Operating System type

Other

### Operating system version

Homey

### Describe the bug

Hey @bropat 

In the latest version i see a lot of errors coming in.
Any idea what's going on?

```
[EufyLibrary] Non-parsable parameter value received from eufy cloud. Will be ignored. { type: 1138, value: '21' }
[EufyLibrary] JSON parse error {
  data: '�',
  error: SyntaxError: Unexpected token � in JSON at position 0
      at JSON.parse (<anonymous>)
      at parseJSON (/node_modules/eufy-security-client/build/utils.js:147:21)
      at Function.readValue (/node_modules/eufy-security-client/build/http/parameter.js:30:63)
      at BatteryDoorbellCamera.updateRawProperty (/node_modules/eufy-security-client/build/http/device.js:127:57)
      at /node_modules/eufy-security-client/build/http/device.js:54:22
      at Array.forEach (<anonymous>)
      at BatteryDoorbellCamera.update (/node_modules/eufy-security-client/build/http/device.js:53:35)
      at EufySecurity.updateDevice (/node_modules/eufy-security-client/build/eufysecurity.js:344:44)
      at EufySecurity.handleDevices (/node_modules/eufy-security-client/build/eufysecurity.js:560:22)
      at HTTPApi.<anonymous> (/node_modules/eufy-security-client/build/eufysecurity.js:167:50)
}
```

### To reproduce

Not sure ;)

**Comment by martijnpoppen** [comment]
NVM issue on my side ;)
