### ISSUE TITLE
Support for T8510 Smart Lock

### ISSUE THREAD

**Issue by ms30250** [bropat/eufy-security-client#78]
Submitting a feature/hardware support request for T8510 Smart Lock with wifi bridge. App sees my bridge but does not see/find the T8510 lock connected to it.

**Comment by ms30250** [comment]
Is it normal for the integration to not load when i have no compatible hardware? The only device I have is the bridge and the T8510 lock. I get failed to setup with the following error.

Error setting up entry 192.168.1.108 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/eufy_security/__init__.py", line 52, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 70, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 116, in set_devices
    if await self.async_get_device_properties() == False:
  File "/config/custom_components/eufy_security/coordinator.py", line 133, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by ms30250** [comment]
Turns out the T8510 works perfectly. The addon is using container port 3000 and so is Z-wave-Js. I tried configuring it to use container 3000---->(random) but it didnt seem to work. I moved zwave from 3000---->3000 to 3000--->3500 and everything works.
